apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-falcon
  namespace: istio-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: system:istio-falcon-role
rules:
  - apiGroups: [ "coordination.k8s.io" ]
    resources: [ "leases" ]
    verbs: [ "get", "create", "update", "list", "put","watch" ]
  - apiGroups: [ "" ]
    resources: [ "configmaps", "endpoints","events","services/status", "leases" ]
    verbs: [ "*" ]
  - apiGroups: [ "" ]
    resources: [ "nodes", "services" ]
    verbs: [ "list","get","watch","update" ]
  - apiGroups: [ "apiextensions.k8s.io" ]
    resources: [ "customresourcedefinitions" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "config.istio.io","security.istio.io","networking.istio.io","authentication.istio.io","rbac.istio.io" ]
    resources: [ "*" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "networking.istio.io" ]
    verbs: [ "get", "watch", "list" ]
    resources: [ "gateways" ]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system:istio-falcon-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:istio-falcon-role
subjects:
  - kind: ServiceAccount
    name: istio-falcon
    namespace: istio-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: istio-falcon-ds
  namespace: istio-system
spec:
  selector:
    matchLabels:
      name: istio-falcon-ds
  template:
    metadata:
      labels:
        name: istio-falcon-ds
    spec:
      affinity:                              
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/master
                    operator: Exists
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: Exists
      containers:
        - name: istio-falcon
          image: njfanxun/istio-falcon:latest
          imagePullPolicy: IfNotPresent
          args:
            - mgr
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
                - SYS_TIME
      serviceAccountName: istio-falcon
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists